Repository googleapis/nodejs-asset, pull requests merged in 2019-05, with the labels that each got.

#133 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#134 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#135 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#138 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: automerge, cla: yes

#139 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#137 build: only pipe to codecov if tests run in Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#140 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#143 feat: introduces 'expression text', deprecates version field
  samples/package.json
  src/v1/doc/google/iam/v1/doc_policy.js
  src/v1/doc/google/type/doc_expr.js
  src/v1beta1/doc/google/iam/v1/doc_policy.js
  src/v1beta1/doc/google/type/doc_expr.js
  synth.metadata
Labels: cla: yes

#144 build: add GitHub action for triggering deployments
  .github/main.workflow
Labels: cla: yes

#147 docs(test): removed exception for docs now on master
  package.json
Labels: cla: yes

#148 docs: update quickstart sample in README
  README.md
  synth.metadata
Labels: cla: yes

#150 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#151 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1/asset_service_client.js
  src/v1beta1/asset_service_client.js
  synth.metadata
Labels: cla: yes

#152 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#153 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#154 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#155 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
