Repository googleapis/nodejs-asset, pull requests merged in 2020-11, with the labels that each got.

#412 feat: add AnalyzeIamPolicy and AnalyzeIamPolicyLongrunning RPCs
  protos/google/cloud/asset/v1/asset_service.proto
  protos/google/cloud/asset/v1/assets.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/asset_service_client.ts
  src/v1/asset_service_client_config.json
  synth.metadata
  test/gapic_asset_service_v1.ts
Labels: api: cloudasset, cla: yes, context: full

#414 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#418 build: add type for AssetServiceClient
  src/index.ts
  synth.metadata
Labels: api: cloudasset, cla: yes, context: none

#422 test: failures appear to be timing related
  samples/test/sample.test.js
Labels: api: cloudasset, cla: yes

#419 fix: do not modify options object, use defaultScopes
  package.json
  src/v1/asset_service_client.ts
  src/v1beta1/asset_service_client.ts
  src/v1p1beta1/asset_service_client.ts
  src/v1p2beta1/asset_service_client.ts
  src/v1p4beta1/asset_service_client.ts
  src/v1p5beta1/asset_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: cloudasset, cla: yes

#421 build: sync metadata
  synth.metadata
Labels: api: cloudasset, cla: yes, context: full

#426 test: turn on some test, turn off others
  samples/test/sample.test.js
Labels: api: cloudasset, cla: yes

#428 build: update to protos.json
  protos/protos.json
  synth.metadata
Labels: api: cloudasset, cla: yes, context: none

#431 chore: address linting issues
  src/v1p1beta1/asset_service_client.ts
  synth.metadata
Labels: api: cloudasset, cla: yes, context: none

#435 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full
