Repository googleapis/nodejs-asset, pull requests merged in 2020-06, with the labels that each got.

#334 build: update protos.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#337 feat: move ts target to es2018 from es2016
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v1/asset_service_client.ts
  src/v1beta1/asset_service_client.ts
  src/v1p1beta1/asset_service_client.ts
  src/v1p2beta1/asset_service_client.ts
  src/v1p4beta1/asset_service_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#342 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#344 fix: handle fallback option properly
  src/v1/asset_service_client.ts
  src/v1beta1/asset_service_client.ts
  src/v1p1beta1/asset_service_client.ts
  src/v1p2beta1/asset_service_client.ts
  src/v1p4beta1/asset_service_client.ts
  synth.metadata
Labels: cla: yes, context: none

#343 feat: add sample code for SearchAllResources and SearchAllIamPolicies
  samples/package.json
  samples/searchAllIamPolicies.js
  samples/searchAllResources.js
  samples/test/sample.test.js
Labels: cla: yes

#346 feat: added support for condition in Feed
  README.md
  protos/google/cloud/asset/v1/asset_service.proto
  protos/google/cloud/asset/v1/assets.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  samples/README.md
  src/v1/asset_service_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#348 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#349 feat: add v1p5beta1 API surface
  protos/google/cloud/asset/v1p5beta1/asset_service.proto
  protos/google/cloud/asset/v1p5beta1/assets.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/index.ts
  src/v1p5beta1/asset_service_client.ts
  src/v1p5beta1/asset_service_client_config.json
  src/v1p5beta1/asset_service_proto_list.json
  src/v1p5beta1/index.ts
  synth.metadata
  synth.py
  test/gapic_asset_service_v1p5beta1.ts
Labels: cla: yes
