Repository googleapis/nodejs-asset, pull requests merged in 2020-07, with the labels that each got.

#351 chore: update gitattributes
  .gitattributes
  synth.metadata
Labels: cla: yes, context: none

#353 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#352 build: use bazel build
  src/index.ts
  src/v1/asset_service_client_config.json
  src/v1/asset_service_proto_list.json
  src/v1beta1/asset_service_client_config.json
  src/v1beta1/asset_service_proto_list.json
  src/v1p1beta1/asset_service_client_config.json
  src/v1p1beta1/asset_service_proto_list.json
  src/v1p2beta1/asset_service_client_config.json
  src/v1p2beta1/asset_service_proto_list.json
  src/v1p4beta1/asset_service_client_config.json
  src/v1p4beta1/asset_service_proto_list.json
  src/v1p5beta1/asset_service_proto_list.json
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#355 feat(samples): add sample code for ListAssets v1p5beta1
  samples/listAssets.js
  samples/test/sample.test.js
Labels: cla: yes

#360 build: typo in gitattribute
  .gitattributes
  README.md
  samples/README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#362 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#363 chore: update generated protos.js
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#368 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#367 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#369 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#370 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#371 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#373 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#374 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#375 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
