Repository googleapis/nodejs-asset, pull requests merged in 2020-05, with the labels that each got.

#326 fix: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#327 feat: clean proto list, add decoded function for longrunning method
  src/v1/asset_service_client.ts
  src/v1beta1/asset_service_client.ts
  src/v1p4beta1/asset_service_client.ts
  synth.metadata
  synth.py
  test/gapic_asset_service_v1.ts
  test/gapic_asset_service_v1beta1.ts
  test/gapic_asset_service_v1p1beta1.ts
  test/gapic_asset_service_v1p2beta1.ts
  test/gapic_asset_service_v1p4beta1.ts
Labels: cla: yes

#328 feat: check status of long running operation by its name
  synth.metadata
Labels: automerge, cla: yes

#329 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#332 feat: add `SearchAllResources` and `SearchAllIamPolicies` rpcs in asset service proto
  package.json
  protos/google/cloud/asset/v1/asset_service.proto
  protos/google/cloud/asset/v1/assets.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/asset_service_client.ts
  src/v1/asset_service_client_config.json
  synth.metadata
  test/gapic_asset_service_v1.ts
Labels: cla: yes

#333 docs: Properly format literal strings.
  protos/google/cloud/asset/v1/assets.proto
  synth.metadata
Labels: cla: yes, context: full
