Repository googleapis/nodejs-asset, pull requests merged in 2021-06, with the labels that each got.

#502 chore(nodejs): remove api-extractor dependencies
  package.json
Labels: api: cloudasset, automerge, cla: yes

#504 build: use correct headers for REST requests, update proto list
  src/v1/asset_service_client.ts
  src/v1/asset_service_proto_list.json
  src/v1p1beta1/asset_service_client.ts
  src/v1p2beta1/asset_service_client.ts
  src/v1p4beta1/asset_service_client.ts
  src/v1p5beta1/asset_service_client.ts
  src/v1p5beta1/asset_service_proto_list.json
Labels: api: cloudasset, cla: yes

#505 CloudAsset: Update asset lib to v1 for ListAssets sample code
  samples/listAssets.js
Labels: api: cloudasset, cla: yes, samples

#515 samples: reduce calls to API
  samples/test/sample.test.js
Labels: api: cloudasset, cla: yes

#514 fix(deps): google-gax v2.17.0 with mTLS
  package.json
Labels: api: cloudasset, automerge, cla: yes
